---
title: "Tree Construction"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message=FALSE, warning=FALSE}
library(ape)
library(ctv)
update.views('Phylogenetics')
```




## Tree Construction: 

* loading the result. 

```{r}
DistanceMatrix = as.matrix(read.table('Bottleneck_Dist.txt', sep = ','))
#Data = read.csv2(file = 'Bottleneck_Dist.csv', sep = ';', encoding = 'utf-8')
labels = c('A/turkey/Ontario/FAV110-4/2009(H1N1)',
 'A/mallard/Nova_Scotia/00088/2010(H1N1)',
 'A/thick-billed_murre/Canada/1871/2011(H1N1)',
 'A/duck/Guangxi/030D/2009(H1N1)',
 'A/mallard/France/691/2002(H1N1)',
 'A/duck/Hokkaido/w73/2007(H1N1)',
 'A/pintail/Miyagi/1472/2008(H1N1)',
 'A/mallard/Korea/KNU_YP09/2009(H1N1)',
 'A/mallard/Maryland/352/2002(H1N1)',
 'A/mallard/Maryland/26/2003(H1N1)',
 'A/dunlin/Alaska/44421-660/2008(H1N1)',
 'A/mallard/Minnesota/Sg-00620/2008(H1N1)',
 'A/turkey/Virginia/4135/2014(H1N1)',
 'A/chicken/Eastern_China/XH222/2008(H5N1)',
 'A/duck/Eastern_China/JS017/2009(H5N1)',
 'A/chicken/Yunnan/chuxiong01/2005(H5N1)',
 'A/chicken/Germany/R3234/2007(H5N1)',
 'A/domestic_duck/Germany/R1772/2007(H5N1)',
 'A/wild_bird/Hong_Kong/07035-1/2011(H5N1)',
 'A/Chicken/Hong_Kong/822.1/01_(H5N1)',
 'A/chicken/Miyazaki/10/2011(H5N1)',
 'A/chicken/Korea/es/2003(H5N1)',
 'A/mandarin_duck/Korea/K10-483/2010(H5N1)',
 'A/turkey/VA/505477-18/2007(H5N1)',
 'A/American_black_duck/NB/2538/2007(H7N3)',
 'A/American_black_duck/New_Brunswick/02490/2007(H7N3)',
 'A/American_green-winged_teal/California/44242-906/2007(H7N3)',
 'A/avian/Delaware_Bay/226/2006(H7N3)',
 'A/chicken/British_Columbia/GSC_human_B/04(H7N3)',
 'A/chicken/Rizhao/713/2013(H7N9)',
 'A/chicken/Jiangsu/1021/2013(H7N9)',
 'A/duck/Jiangxi/3096/2009(H7N9)',
 'A/wild_duck/Korea/SH19-47/2010(H7N9)',
 'A/turkey/Minnesota/1/1988(H7N9)',
 'A/mallard/Minnesota/AI09-3770/2009(H7N9)',
 'A/mallard/Postdam/178-4/1983(H2N2)',
 'A/duck/Hong_Kong/319/1978(H2N2)',
 'A/emperor_goose/Alaska/44297-260/2007(H2N2)')
```




```{r}
## assign label names to matrix: 
row.names(DistanceMatrix) = labels 
colnames(DistanceMatrix) = labels
## convert to distance format 
MyDistanceMat = as.dist(DistanceMatrix)
```



# Buidling a neighbor-joining (nj) tree: 

* Neighbor Joining is one of the most common ways to build a tree using molecular data that’s been converted to sequences; its one of the options within BLAST.

* Build the tree with `nj()`: 


```{r, fig.height=30, fig.width=15, fig.align="center"}
png('tree_flu.png', width = 800, height = 1200)
NJ_tree = ape::nj(MyDistanceMat)
plot(NJ_tree)
```