---
title: "Landscape Construction"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message=FALSE, warning=FALSE}
library(ape)
library(ctv)
library(phangorn)
library(seqinr)
### 
library(TDA)
library("stringr")
library(tidyverse)
library("jsonlite")
library(gtools)
```

# Diagrams H0 order: 

```{r, message=FALSE, warning=FALSE}
path = paste(getwd(),"/H0", sep ="")
setwd(path)
files_list = mixedsort(list.files(path, pattern = '.txt')) ## sorting the text files 
print(files_list)

## storing the data in the list
datasH0 = list()
for (i in seq_along(files_list)){
  file = files_list[i]
  data = read.table(file, sep = ",")
  dimvalue = replicate(nrow(data), 0) # all order 0's
  data = cbind(dimvalue, data)
  datasH0[[i]] = data
}
```


# Diagrams H1 order: 

```{r, message=FALSE, warning=FALSE} 
path = paste(getwd(),"/H1", sep ="")
setwd(path)
files_list = mixedsort(list.files(path, pattern = '.txt')) ## sorting the text files 
print(files_list)

## storing the data in the list
datasH1 = list()
for (i in seq_along(files_list)){
  file = files_list[i]
  data = read.table(file, sep = ",")
  dimvalue = replicate(nrow(data), 1) # all dimension order 1's
  data = cbind(dimvalue, data)
  datasH1[[i]] = data
}
```


# Combining them together into Diagrams: 

```{r}
datas = list()
colvals = c("dimension", "Birth", "Death")
for (i in seq_along(1:38)){
  first = datasH0[[i]]
  second = datasH1[[i]]
  datafile = rbind(first,second)
  matFile = as.matrix(datafile)
  colnames(matFile) = colvals
  datas[[i]] = matFile
}
```

# Persistent Landscape: 


```{r}
computeLandScape = function(datas){
    n = length(datas)
    Landscapes = list()
    maxscale = 5
    for (i in seq_along((1:38))){
      data = datas[[i]]
      tseq = seq(0,maxscale, length = 1000)
      value = landscape(data, dimension = 1, KK = 1)
      Landscapes[[i]] = value
    }
  return(Landscapes)
  }
```



# Computing: 

```{r}
#landscapes = computeLandScape(datas)
DiagLim = datas[[1]]


landscape(DiagLim, dimension = 1, KK = 1, tseq = tseq)
```


# Wasserstein distance matrix: 

* We consider compute the Wasserstein distance matrix: 


```{r, message=FALSE}
library(transport)
```

```{r}
ptm = proc.time()
wasserstein1d(landscapes[[1]], landscapes[[2]])
proc.time() - ptm
```

* Function to compute the distance matrix of Wasserstein distance: 

```{r}
WassersteinDist = function(datas, size){
  DistMat = matrix(rep(0,size*size), nrow = size)
  slicing = size 
  for (i in 1:(slicing-1)){
    for (j in (i+1):slicing){
      val_i = datas[[i]]
      val_j = datas[[j]]
      DistMat[i,j] = wasserstein1d(val_i,val_j)
    }
  }
  output = DistMat + t(DistMat)
  return(output)
}

```



# Computing the distance matrix: 

```{r}
DistMat = WassersteinDist(landscapes,38)
```

* Label Types: 

```{r}
labels=c('A/turkey/Ontario/FAV110-4/2009(H1N1)',
 'A/mallard/Nova_Scotia/00088/2010(H1N1)',
 'A/thick-billed_murre/Canada/1871/2011(H1N1)',
 'A/duck/Guangxi/030D/2009(H1N1)',
 'A/mallard/France/691/2002(H1N1)',
 'A/duck/Hokkaido/w73/2007(H1N1)',
 'A/pintail/Miyagi/1472/2008(H1N1)',
 'A/mallard/Korea/KNU_YP09/2009(H1N1)',
 'A/mallard/Maryland/352/2002(H1N1)',
 'A/mallard/Maryland/26/2003(H1N1)',
 'A/dunlin/Alaska/44421-660/2008(H1N1)',
 'A/mallard/Minnesota/Sg-00620/2008(H1N1)',
 'A/turkey/Virginia/4135/2014(H1N1)',
 'A/chicken/Eastern_China/XH222/2008(H5N1)',
 'A/duck/Eastern_China/JS017/2009(H5N1)',
 'A/chicken/Yunnan/chuxiong01/2005(H5N1)',
 'A/chicken/Germany/R3234/2007(H5N1)',
 'A/domestic_duck/Germany/R1772/2007(H5N1)',
 'A/wild_bird/Hong_Kong/07035-1/2011(H5N1)',
 'A/Chicken/Hong_Kong/822.1/01_(H5N1)',
 'A/chicken/Miyazaki/10/2011(H5N1)',
 'A/chicken/Korea/es/2003(H5N1)',
 'A/mandarin_duck/Korea/K10-483/2010(H5N1)',
 'A/turkey/VA/505477-18/2007(H5N1)',
 'A/American_black_duck/NB/2538/2007(H7N3)',
 'A/American_black_duck/New_Brunswick/02490/2007(H7N3)',
 'A/American_green-winged_teal/California/44242-906/2007(H7N3)',
 'A/avian/Delaware_Bay/226/2006(H7N3)',
 'A/chicken/British_Columbia/GSC_human_B/04(H7N3)',
 'A/chicken/Rizhao/713/2013(H7N9)',
 'A/chicken/Jiangsu/1021/2013(H7N9)',
 'A/duck/Jiangxi/3096/2009(H7N9)',
 'A/wild_duck/Korea/SH19-47/2010(H7N9)',
 'A/turkey/Minnesota/1/1988(H7N9)',
 'A/mallard/Minnesota/AI09-3770/2009(H7N9)',
 'A/mallard/Postdam/178-4/1983(H2N2)',
 'A/duck/Hong_Kong/319/1978(H2N2)',
 'A/emperor_goose/Alaska/44297-260/2007(H2N2)')
```



* Make the matrix: 


```{r}
row.names(DistMat) = labels 
colnames(DistMat) = labels
## convert to distance format 
MyDistanceMat = as.dist(DistanceMatrix)
```


* Construct the tree: UMPGA method. 

```{r}
png('tree_flu_upgma_chaos_H1_persistence_landscapes.png', width = 1200, height = 1500)
UMPGA_tree = upgma(MyDistanceMat)
plot(UMPGA_tree, main = "UMPGA:H1-ChaosReps-Persistence-Landscape")
```




