---
title: 'Tree Construction: Chaos Representation Experiement on the exponent order
  Wasserstein'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r, message=FALSE, warning = FALSE}
library(ape)
library(ctv)
library(phangorn)
library(seqinr)
```

* Label Types: 

```{r}
labels=c('A/turkey/Ontario/FAV110-4/2009(H1N1)',
 'A/mallard/Nova_Scotia/00088/2010(H1N1)',
 'A/thick-billed_murre/Canada/1871/2011(H1N1)',
 'A/duck/Guangxi/030D/2009(H1N1)',
 'A/mallard/France/691/2002(H1N1)',
 'A/duck/Hokkaido/w73/2007(H1N1)',
 'A/pintail/Miyagi/1472/2008(H1N1)',
 'A/mallard/Korea/KNU_YP09/2009(H1N1)',
 'A/mallard/Maryland/352/2002(H1N1)',
 'A/mallard/Maryland/26/2003(H1N1)',
 'A/dunlin/Alaska/44421-660/2008(H1N1)',
 'A/mallard/Minnesota/Sg-00620/2008(H1N1)',
 'A/turkey/Virginia/4135/2014(H1N1)',
 'A/chicken/Eastern_China/XH222/2008(H5N1)',
 'A/duck/Eastern_China/JS017/2009(H5N1)',
 'A/chicken/Yunnan/chuxiong01/2005(H5N1)',
 'A/chicken/Germany/R3234/2007(H5N1)',
 'A/domestic_duck/Germany/R1772/2007(H5N1)',
 'A/wild_bird/Hong_Kong/07035-1/2011(H5N1)',
 'A/Chicken/Hong_Kong/822.1/01_(H5N1)',
 'A/chicken/Miyazaki/10/2011(H5N1)',
 'A/chicken/Korea/es/2003(H5N1)',
 'A/mandarin_duck/Korea/K10-483/2010(H5N1)',
 'A/turkey/VA/505477-18/2007(H5N1)',
 'A/American_black_duck/NB/2538/2007(H7N3)',
 'A/American_black_duck/New_Brunswick/02490/2007(H7N3)',
 'A/American_green-winged_teal/California/44242-906/2007(H7N3)',
 'A/avian/Delaware_Bay/226/2006(H7N3)',
 'A/chicken/British_Columbia/GSC_human_B/04(H7N3)',
 'A/chicken/Rizhao/713/2013(H7N9)',
 'A/chicken/Jiangsu/1021/2013(H7N9)',
 'A/duck/Jiangxi/3096/2009(H7N9)',
 'A/wild_duck/Korea/SH19-47/2010(H7N9)',
 'A/turkey/Minnesota/1/1988(H7N9)',
 'A/mallard/Minnesota/AI09-3770/2009(H7N9)',
 'A/mallard/Postdam/178-4/1983(H2N2)',
 'A/duck/Hong_Kong/319/1978(H2N2)',
 'A/emperor_goose/Alaska/44297-260/2007(H2N2)')
```




```{r}
getwd()
```

## For Diagrams H0: 

* Make the matrix: 


```{r}
DistH0_1 = as.matrix(read.table('1_order_H0_DistMat.txt', sep =','))
row.names(DistH0_1) = labels 
colnames(DistH0_1) = labels
## convert to distance format 
DistH0_1= as.dist(DistH0_1)


DistH0_2 = as.matrix(read.table('2_order_H0_DistMat.txt', sep =','))
row.names(DistH0_2) = labels 
colnames(DistH0_2) = labels
## convert to distance format 
DistH0_2= as.dist(DistH0_2)


DistH0_3 = as.matrix(read.table('3_order_H0_DistMat.txt', sep =','))
row.names(DistH0_3) = labels 
colnames(DistH0_3) = labels
## convert to distance format 
DistH0_3= as.dist(DistH0_3)


DistH0_4 = as.matrix(read.table('4_order_H0_DistMat.txt', sep =','))
row.names(DistH0_4) = labels 
colnames(DistH0_4) = labels
## convert to distance format 
DistH0_4= as.dist(DistH0_4)


DistH0_5 = as.matrix(read.table('5_order_H0_DistMat.txt', sep =','))
row.names(DistH0_5) = labels 
colnames(DistH0_5) = labels
## convert to distance format 
DistH0_5= as.dist(DistH0_5)
```





* Construct the tree: UMPGA method. 

```{r}
png('tree_flu_upgma_chaosrep_H0_1.png', width = 1200, height = 1500)
UMPGA_tree = upgma(DistH0_1)
plot(UMPGA_tree, main = "Tree.Influenza.H0.exponent_order_1.UMPGA")

png('tree_flu_upgma_chaosrep_H0_2.png', width = 1200, height = 1500)
UMPGA_tree = upgma(DistH0_2)
plot(UMPGA_tree, main = "Tree.Influenza.H0.exponent_order_2.UMPGA")

png('tree_flu_upgma_chaosrep_H0_3.png', width = 1200, height = 1500)
UMPGA_tree = upgma(DistH0_3)
plot(UMPGA_tree, main = "Tree.Influenza.H0.exponent_order_3.UMPGA")

png('tree_flu_upgma_chaosrep_H0_4.png', width = 1200, height = 1500)
UMPGA_tree = upgma(DistH0_4)
plot(UMPGA_tree, main = "Tree.Influenza.H0.exponent_order_4.UMPGA")

png('tree_flu_upgma_chaosrep_H0_5.png', width = 1200, height = 1500)
UMPGA_tree = upgma(DistH0_5)
plot(UMPGA_tree, main = "Tree.Influenza.H0.exponent_order_5.UMPGA")
```


* The distance matrices with diagram $H_{0}$ have all entries $0's$ so it is not sufficiently significant to construct the tree based on diagram $H_{0}$. 


# For diagram $H_{1}$. 


* Make the matrix: 


```{r}
DistH1_1 = as.matrix(read.table('1_order_H1_DistMat.txt', sep =','))
row.names(DistH1_1) = labels 
colnames(DistH1_1) = labels
## convert to distance format 
DistH1_1= as.dist(DistH1_1)


DistH1_2 = as.matrix(read.table('2_order_H1_DistMat.txt', sep =','))
row.names(DistH1_2) = labels 
colnames(DistH1_2) = labels
## convert to distance format 
DistH1_2= as.dist(DistH1_2)


DistH1_3 = as.matrix(read.table('3_order_H1_DistMat.txt', sep =','))
row.names(DistH1_3) = labels 
colnames(DistH1_3) = labels
## convert to distance format 
DistH1_3= as.dist(DistH1_3)


DistH1_4 = as.matrix(read.table('4_order_H1_DistMat.txt', sep =','))
row.names(DistH1_4) = labels 
colnames(DistH1_4) = labels
## convert to distance format 
DistH1_4= as.dist(DistH1_4)


DistH1_5 = as.matrix(read.table('5_order_H1_DistMat.txt', sep =','))
row.names(DistH1_5) = labels 
colnames(DistH1_5) = labels
## convert to distance format 
DistH1_5= as.dist(DistH1_5)
```





* Construct the tree: UMPGA method. 

```{r}
png('tree_flu_upgma_chaosrep_H1_1.png', width = 1200, height = 1500)
UMPGA_tree = upgma(DistH1_1)
plot(UMPGA_tree, main = "Tree.Influenza.H1.exponent_order_1.UMPGA")
```

```{r}
png('tree_flu_upgma_chaosrep_H1_2.png', width = 1200, height = 1500)
UMPGA_tree = upgma(DistH1_2)
plot(UMPGA_tree, main = "Tree.Influenza.H1.exponent_order_2.UMPGA")
```

```{r}
png('tree_flu_upgma_chaosrep_H1_3.png', width = 1200, height = 1500)
UMPGA_tree = upgma(DistH1_3)
plot(UMPGA_tree, main = "Tree.Influenza.H1.exponent_order_3.UMPGA")
```

```{r}
png('tree_flu_upgma_chaosrep_H1_4.png', width = 1200, height = 1500)
UMPGA_tree = upgma(DistH1_4)
plot(UMPGA_tree, main = "Tree.Influenza.H1.exponent_order_4.UMPGA")
```

```{r}
png('tree_flu_upgma_chaosrep_H1_5.png', width = 1200, height = 1500)
UMPGA_tree = upgma(DistH1_5)
plot(UMPGA_tree, main = "Tree.Influenza.H1.exponent_order_5.UMPGA")
```
